---
title: "Simulation study 1"
author: "Tetiana Gorbach"
date: "2/23/2021"
output:
  pdf_document: default
  toc: yes
  toc_depth: 2
  html_document: default
---

```{r setup, include=FALSE}
require(tidyverse)
require(gridExtra)
require(rsimsum)
require(xtable)
require(gridExtra) # for ggplot

```
\tableofcontents

```{r, read results, echo=F}
load("../results/res2022_12_13_17_24_52.Rdata")
sim.results <- as.data.frame(sim.results)
```

Transform to a long format:

```{r}
sim.results.long <- sim.results %>%
  dplyr::select(dgp, alpha1,
    beta1,  gamma1, gamma2, n, 
    FD = est.fd.semipar, `FD TD` = est.eif.fd.td.semipar,
    BD = est.bd.semipar, `BD TD` = est.eif.td.bd.semipar,
    TD = est.td.semipar, `BD FD TD` = est.eif.all.semipar
  ) %>%
  gather(method, ate.est, FD:`BD FD TD`, factor_key = TRUE) %>%
  group_by(dgp, n, method) %>%
  summarise(
    alpha = mean(alpha1),
    beta = mean(beta1),
    gamma1 = mean(gamma1),
    gamma2 = mean(gamma2),
    sc.emp.var = var(sqrt(n) * ate.est)
  ) %>%
  ungroup()
```

Calculate performance measures:
```{r}
sim.results.bias <- sim.results %>%
  dplyr::select(dgp, n, alpha = alpha1, beta = beta1, gamma1, gamma2,
    `FD` = est.fd.semipar, `FD TD` = est.eif.fd.td.semipar,
    `BD` = est.bd.semipar, `BD TD` = est.eif.td.bd.semipar,
    `TD` = est.td.semipar, `BD FD TD` = est.eif.all.semipar
  ) %>%
  gather(method, ate.est, `FD`:`BD FD TD`, factor_key = TRUE) %>%
  group_by(dgp, n, method) %>%
  summarise(
    sc.emp.var = var(sqrt(n) * ate.est)
  )
sim.results.bounds <- sim.results %>%
  dplyr::select(dgp, alpha = alpha1,
    beta = beta1, gamma1, gamma2, n) %>%
  group_by(dgp) %>%
  summarise(
    alpha = mean(alpha),
    beta = mean(beta),
    gamma1 = mean(gamma1),
    gamma2 = mean(gamma2)
  )
sim <- merge(sim.results.bias, sim.results.bounds) %>%
  mutate(
    mc.se.of.sc.emp.var = sqrt(2 * sc.emp.var^2 / number.of.replicates)) %>%
  arrange(dgp, method, n)
rm(sim.results.bias, sim.results.bounds)
```

# Figure
```{r}
cbbPalette <- c("#E69F00", "#D55E00", "#56B4E9", "#0072B2", "#009E73", "#000000") # colorblind-friendly palette
names(cbbPalette) <- levels(sim.results.long$method)[!levels(sim.results.long$method) == "naive"] # naive estimator is not included in the figure
shapes <- 1:6
names(shapes) <- levels(sim.results.long$method)[!levels(sim.results.long$method) == "naive"] # naive estimator is not included in the figure

p1 <- sim  %>%
   mutate(
                alpha_gamma2 = paste0("list(alpha==", alpha, ", gamma[2]==", gamma2,")"),
                beta_gamma1 = paste0("list(beta==", beta, ", gamma[1]==", gamma1,")")
        )%>%
  ggplot(aes(x = n, y = sc.emp.var)) +
  geom_ribbon(aes(
    ymin = sc.emp.var - qnorm(0.975) * mc.se.of.sc.emp.var,
    ymax = sc.emp.var + qnorm(0.975) * mc.se.of.sc.emp.var,
    group = method, fill = method
  ),
  linetype = 1, alpha = 0.2
  ) +
  geom_line(aes(group = method, col = method), size = 0.3, linetype = 1) +
  geom_point(aes(shape = method, col = method), size = 0.5) +
  facet_grid( alpha_gamma2~ beta_gamma1,
    scales = "free",
    labeller = label_parsed
  ) +
  labs(y = "Scaled empirical variance", x = "Sample size") +
  theme_bw() +
  theme(
    text = element_text(size = 6),
    axis.title = element_text(size = 8),
    strip.text = element_text(size = 8)
  ) +
  scale_shape_manual(values = shapes) +
  scale_colour_manual(values = cbbPalette) +
  scale_fill_manual(values = cbbPalette) +
  theme(
    legend.key.size = unit(2, "line"),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  guides(colour = guide_legend(nrow = 1),
         shape = guide_legend(nrow = 1))




g_legend <- function(a.gplot) {
  tmp <- ggplot_gtable(ggplot_build(a.gplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)
}

mylegend <- g_legend(p1) 
grid.arrange(arrangeGrob(p1 + theme(legend.position = "none"),
  nrow = 1),
mylegend,
nrow = 2, heights = c(10, 1)
)



pdf("Figure_sim_study_mv_cov.pdf", height = 5, width = 6)
grid.arrange(arrangeGrob(p1 + theme(legend.position = "none"),
  nrow = 1),
mylegend,
nrow = 2, heights = c(10, 1)
)
dev.off()

```

# DGP vs parameters
```{r}
print(xtable(sim.results %>%
  dplyr::select(dgp, alpha1, beta1, gamma1, gamma2) %>%
  group_by(dgp) %>%
  summarise(
          alpha = mean(alpha1),
    beta = mean(beta1),
    gamma1 = mean(gamma1),
    gamma2 = mean(gamma2)
  ),
digits = c(0, 0, 1, 1, 1,1), align = rep("r", 6)
),
include.rownames = F
)
```

# Scaled empirical variance
```{r}
print(xtable(sim %>%
  mutate(estim = paste0(format(round(sc.emp.var, digits = 3), nsmall = 3), " (", format(round(mc.se.of.sc.emp.var, digits = 3), nsmall = 3), ")")) %>%
  select(dgp, n, method, estim) %>%
  spread(method, estim) %>%
  select(dgp, n, BD, FD, TD, `BD TD`, `FD TD`, `BD FD TD`),
align = rep("r", 9),
digits = 0
),
include.rownames = F
)
```









